### ISSUE TITLE
Wrong database credentials on installer loses all installer fields

### ISSUE THREAD

**Issue by juanluisbaptiste** [ladybirdweb/agorainvoicing#745]
Hi,

While running the installer I noticed that after clicking on the "Setup Application" and there is a wrong database connection value, the wizard will show the error but it also will start over the installation wizard instead of respecting the already entered values. 

I also thought that the "Setup database" button would do a connection check first before continuing with the installation, it would make more sense.

This is with latest 1.0.22 version.

**Comment by ashu555** [comment]
Fixed in Latest Release

**Comment by juanluisbaptiste** [comment]
I still see the problem.

1. Put a name to the app and click setup application
2. Fill in database fields but put a wrong password and click again on setup application
3. Click on install

Installer goes back to the fist page but the app name is empty, also the database settings on the next page.

Testing 1.0.24 release.

**Comment by juanluisbaptiste** [comment]
Also, may I ask again, to do a manual setup by putting a prefilled ._env_ file in the app  root dir and manually seeding the database, could you show me the commands to seed all the database tables?

Thanks.
